FROM node:20-alpine

WORKDIR /nodejs2025

# Copy package.json & install dependencies (cả dev)
COPY package*.json ./
RUN npm install

# Copy toàn bộ source
COPY . .

# Expose port backend
EXPOSE 5000

# CMD chạy dev
CMD ["npm", "run", "dev"]